env: development
ktor:
  deployment:
    port: "$PORT:8080"
  development: true
  application:
    modules:
      - org.dotsdev.iluva.ApplicationKt.module

database:
  host: "localhost"
  port: "5432"
  username: "postgres"
  password: "postgres"
  name: "postgres"
  schema: "iluva"
  maxPollSize: 4
  isReadOnly: false
  type: "POSTGRES"

jwt:
  issuer: "http://localhost/"
  secret: "iluva"
  audience: "iluva-api"
  realm: "iluva"